AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Tabletop Beholder Service

Parameters:

  CognitoDomain:
    Type: String
    Description: A name for the Cognito Domain

  S3Bucket:
    Type: String
    Description: Parameter to specify the S3 Bucket to use for deployment

  FrontendDeployment:
    Default: remote
    Type: String
    AllowedValues:
      - local
      - remote
    ConstraintDescription: Must specify 'local' or 'remote' for FrontendDeployment.

Conditions:
  DeployCloudFront: !Equals
    - !Ref FrontendDeployment
    - remote

Globals:
  Function:
    Timeout: 20

  Api:
    Cors:
      AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
      AllowHeaders: "'content-type,authorization'"
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      AddDefaultAuthorizerToCorsPreflight: false
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: !GetAtt UserPool.Arn

Resources:

  #-----------------------------------------------------
  # Cognito Configuration for user management
  #-----------------------------------------------------
  
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UsernameAttributes:
        - email
      UsernameConfiguration: 
        CaseSensitive: false
      AutoVerifiedAttributes:
        - email
      UserPoolName: !Sub ${CognitoDomain}-user-pool
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: false
          Required: true
        - Name: name
          AttributeDataType: String
          Mutable: true
          Required: true

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      AllowedOAuthFlowsUserPoolClient: true
      CallbackURLs:
        - http://localhost:8000
        - !If
            - DeployCloudFront
            - !Sub "https://${CloudFrontDistribution.DomainName}"
            - !Ref "AWS::NoValue"
      LogoutURLs:
        - http://localhost:8000
        - !If
            - DeployCloudFront
            - !Sub "https://${CloudFrontDistribution.DomainName}"
            - !Ref "AWS::NoValue"
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthScopes:
        - phone
        - email
        - openid
        - profile
      SupportedIdentityProviders:
        - COGNITO
      PreventUserExistenceErrors: ENABLED

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Ref CognitoDomain
      UserPoolId: !Ref UserPool


  #-----------------------------------------------------
  # CloudFront Configuration
  #-----------------------------------------------------

  CloudFrontOriginAccessIdentity:
    Type: 'AWS::CloudFront::CloudFrontOriginAccessIdentity'
    Condition: DeployCloudFront
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: 'Serverless frontend website'

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Condition: DeployCloudFront
    Properties:
      DistributionConfig:
        Comment: "Cloudfront distribution for serverless website"
        DefaultRootObject: "index.html"
        Enabled: true
        HttpVersion: http2
        PriceClass: PriceClass_100
        # List of origins that Cloudfront will connect to
        Origins:
          - Id: s3-website
            DomainName: !Sub "${S3Bucket}.s3.us-east-2.amazonaws.com"
            OriginPath: /static
            S3OriginConfig:
              # Restricting Bucket access through an origin access identity
              OriginAccessIdentity:
                Fn::Sub: 'origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}'
        # To connect the CDN to the origins you need to specify behaviours
        DefaultCacheBehavior:
          # Compress resources automatically ( gzip )
          Compress: 'true'
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          TargetOriginId: s3-website
          ViewerProtocolPolicy : redirect-to-https
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Condition: DeployCloudFront
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        # Restricting access to cloudfront only.
        Statement:
          -
            Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal:
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"


  #-----------------------------------------------------
  # Role/Permissions/Policy Configuration
  #-----------------------------------------------------

  AccessRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaRole'
        - 'arn:aws:iam::aws:policy/AWSLambdaExecute'
      AssumeRolePolicyDocument:
        Version: "2012-10-17" 
        Statement: 
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: 'WriteToCloudWatch'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - cloudwatch:PutMetricData
              Resource: '*'

        - PolicyName: 'AccessEncounterTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Effect: Allow
              Action: dynamodb:*
              Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_EncounterTable"

        - PolicyName: 'AccessSessionTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_SessionTable"
              - Effect: Allow
                Action: dynamodb:query
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_SessionTable/index/SessionsSortBySpellNameIndex"

        - PolicyName: 'AccessCreatureTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_CreatureTable"
              - Effect: Allow
                Action: dynamodb:query
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_CreatureTable/index/CreaturesSortBySpellNameIndex"

        - PolicyName: 'AccessActionTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_ActionTable"
              - Effect: Allow
                Action: dynamodb:query
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_ActionTable/index/ActionsSortBySpellNameIndex"

        - PolicyName: 'AccessSpellTable'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_SpellTable"
              - Effect: Allow
                Action: dynamodb:query
                Resource: !Sub "arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/TabletopBeholder_SpellTable/index/SpellsSortBySpellNameIndex"

  #-----------------------------------------------------
  # Lambda Functions Configuration
  #-----------------------------------------------------

  GetSpellLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessRole.Arn
      CodeUri: app
      Handler: dev.tdwalsh.project.tabletopBeholder.lambda.spell.GetSpellLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        TabletopBeholder:
          Type: Api
          Properties:
            Path: /user/{userEmail}/spell/{spellId}
            Method: get

  GetAllSpellsLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessRole.Arn
      CodeUri: app
      Handler: dev.tdwalsh.project.tabletopBeholder.lambda.spell.GetAllSpellsLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        TabletopBeholder:
          Type: Api
          Properties:
            Path: /user/{userEmail}/spell
            Method: get

  CreateSpellLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessRole.Arn
      CodeUri: app
      Handler: dev.tdwalsh.project.tabletopBeholder.lambda.spell.CreateSpellLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        TabletopBeholder:
          Type: Api
          Properties:
            Path: /user/{userEmail}/spell
            Method: post

  UpdateSpellLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessRole.Arn
      CodeUri: app
      Handler: dev.tdwalsh.project.tabletopBeholder.lambda.spell.UpdateSpellLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        TabletopBeholder:
          Type: Api
          Properties:
            Path: /user/{userEmail}/spell/{spellId}
            Method: put

  DeleteSpellLambda:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt AccessRole.Arn
      CodeUri: app
      Handler: dev.tdwalsh.project.tabletopBeholder.lambda.spell.DeleteSpellLambda::handleRequest
      Runtime: java11
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        TabletopBeholder:
          Type: Api
          Properties:
            Path: /user/{userEmail}/spell/{spellId}
            Method: delete
  #-----------------------------------------------------
  # DynamoDB Configuration
  #-----------------------------------------------------
  
  SessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userEmail"
          AttributeType: "S"
        - AttributeName: "sessionId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userEmail"
          KeyType: "HASH"
        - AttributeName: "sessionId"
          KeyType: "RANGE"
        - AttributeName: "sessionName"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "TabletopBeholder_SessionTable"
      GlobalSecondaryIndexes:
        - IndexName: "SessionsSortBySpellNameIndex"
          KeySchema:
            - AttributeName: "userEmail"
              KeyType: "HASH"
            - AttributeName: "sessionName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"
  EncounterTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userEmail"
          AttributeType: "S"
        - AttributeName: "encounterId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userEmail"
          KeyType: "HASH"
        - AttributeName: "encounterId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "TabletopBeholder_EncounterTable"
  CreatureTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userEmail"
          AttributeType: "S"
        - AttributeName: "creatureId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userEmail"
          KeyType: "HASH"
        - AttributeName: "creatureId"
          KeyType: "RANGE"
        - AttributeName: "creatureName"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "TabletopBeholder_CreatureTable"
      GlobalSecondaryIndexes:
        - IndexName: "CreaturesSortBySpellNameIndex"
          KeySchema:
            - AttributeName: "userEmail"
              KeyType: "HASH"
            - AttributeName: "creatureName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"
  ActionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userEmail"
          AttributeType: "S"
        - AttributeName: "actionId"
          AttributeType: "S"
        - AttributeName: "actionName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userEmail"
          KeyType: "HASH"
        - AttributeName: "actionId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "TabletopBeholder_ActionTable"
      GlobalSecondaryIndexes:
        - IndexName: "ActionsSortBySpellNameIndex"
          KeySchema:
            - AttributeName: "userEmail"
              KeyType: "HASH"
            - AttributeName: "actionName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"
  SpellTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "userEmail"
          AttributeType: "S"
        - AttributeName: "spellId"
          AttributeType: "S"
        - AttributeName: "spellName"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "userEmail"
          KeyType: "HASH"
        - AttributeName: "spellId"
          KeyType: "RANGE"
      BillingMode: PAY_PER_REQUEST
      TableName: "TabletopBeholder_SpellTable"
      GlobalSecondaryIndexes:
        - IndexName: "SpellsSortBySpellNameIndex"
          KeySchema:
            - AttributeName: "userEmail"
              KeyType: "HASH"
            - AttributeName: "spellName"
              KeyType: "RANGE"
          Projection:
            ProjectionType: "KEYS_ONLY"

#-----------------------------------------------------
# The outputs defined below will be printed
#  to the screen after a successful deploy
#-----------------------------------------------------

Outputs:

  CognitoUserPoolId:
    Value: !Ref UserPool
    Description: "The Cognito User Pool ID (COGNITO_USER_POOL_ID)."
  CognitoUserPoolClientId:
    Value: !Ref UserPoolClient
    Description: "The Cognito User Pool Client ID (COGNITO_USER_POOL_CLIENT_ID)."
  CognitoDomain:
    Value: !Sub "${CognitoDomain}.auth.us-east-2.amazoncognito.com"
    Description: "The Cognito Domain (COGNITO_DOMAIN)."

  ApiBaseUrl:
    Description: "API Gateway endpoint base URL for Prod stage (API_BASE_URL)."
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

  CognitoRedirectSignin:
    Description: "The URL of the deployed front-end application (COGNITO_REDIRECT_SIGNIN)."
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Condition: DeployCloudFront
  CognitoRedirectSignout:
    Description: "The URL of the deployed front-end application (COGNITO_REDIRECT_SIGNOUT)."
    Value: !Sub "https://${CloudFrontDistribution.DomainName}"
    Condition: DeployCloudFront
