@startuml

newpage
allowmixing
database DynamoDB
database "EXTERNAL Open5E"

DynamoDB -[hidden]> "EXTERNAL Open5E"

class dynamodb.templateApi.TemplateSpellDao{}
class dynamodb.templateApi.TemplateCreatureDao{}
class dynamodb.templateApi.Open5EClient{}
class dynamodb.dao.SessionDao{}
class dynamodb.dao.EncounterDao{}
class dynamodb.dao.CreatureDao{}
class dynamodb.dao.SpellDao{}

dynamodb.dao.SessionDao -[hidden]> dynamodb.dao.EncounterDao
dynamodb.dao.EncounterDao -[hidden]> dynamodb.dao.CreatureDao
dynamodb.dao.CreatureDao -[hidden]> dynamodb.dao.SpellDao
dynamodb.templateApi.Open5EClient -[hidden]-> dynamodb.templateApi.TemplateCreatureDao
dynamodb.templateApi.Open5EClient -[hidden]-> dynamodb.templateApi.TemplateSpellDao

dynamodb.dao.EncounterDao -[hidden]> dynamodb.templateApi.TemplateCreatureDao
"EXTERNAL Open5E" -[hidden]-> dynamodb.templateApi.TemplateCreatureDao
DynamoDB -[hidden]-> dynamodb.dao.EncounterDao

dynamodb.dao.SessionDao  *-u- DynamoDB
dynamodb.dao.EncounterDao  *-u- DynamoDB
dynamodb.dao.CreatureDao  *-u- DynamoDB
dynamodb.dao.SpellDao  *-u- DynamoDB
dynamodb.templateApi.Open5EClient  *-u- "EXTERNAL Open5E"
dynamodb.templateApi.TemplateSpellDao  *-u- dynamodb.templateApi.Open5EClient
dynamodb.templateApi.TemplateCreatureDao  *-u- dynamodb.templateApi.Open5EClient

class activity.AllSpellActivities{}
class activity.AllEncounterActivities{}
class activity.AllSessionActivities{}
class activity.AllCreatureActivities{}
class activity.TemplateSpellActivities{}
class activity.TemplateCreatureActivities{}
class activity.helpers.CreateObjectHelper{}
class activity.helpers.NameHelper{}

activity.AllSessionActivities -[hidden]> activity.AllEncounterActivities
activity.AllEncounterActivities  -[hidden]> activity.AllCreatureActivities
activity.AllCreatureActivities -[hidden]> activity.AllSpellActivities
activity.AllSpellActivities -[hidden]> activity.TemplateCreatureActivities
activity.TemplateCreatureActivities -[hidden]> activity.TemplateSpellActivities
dynamodb.dao.EncounterDao -[hidden]-> activity.AllEncounterActivities

activity.AllSessionActivities *-u- dynamodb.dao.SessionDao
activity.AllEncounterActivities *-u- dynamodb.dao.EncounterDao
activity.AllCreatureActivities *-u- dynamodb.dao.CreatureDao
activity.AllSpellActivities *-u- dynamodb.dao.SpellDao
activity.TemplateCreatureActivities *-u- dynamodb.templateApi.TemplateCreatureDao
activity.TemplateSpellActivities *-u- dynamodb.templateApi.TemplateSpellDao

class lambda.session.AllSessionLambdas{}
class lambda.encounter.AllEncounterLambdas{}
class lambda.creature.AllCreatureLambdas{}
class lambda.spell.AllSpellLambdas{}
class lambda.templateCreature.AllTemplateCreatureLambdas{}
class lambda.templateSpell.AllTemplateSpellLambdas{}

lambda.session.AllSessionLambdas -[hidden]> lambda.encounter.AllEncounterLambdas
lambda.encounter.AllEncounterLambdas -[hidden]> lambda.creature.AllCreatureLambdas
lambda.creature.AllCreatureLambdas -[hidden]> lambda.spell.AllSpellLambdas
lambda.spell.AllSpellLambdas -[hidden]> lambda.templateCreature.AllTemplateCreatureLambdas
lambda.templateCreature.AllTemplateCreatureLambdas -[hidden]> lambda.templateSpell.AllTemplateSpellLambdas
activity.AllEncounterActivities -[hidden]-> lambda.encounter.AllEncounterLambdas
lambda.session.AllSessionLambdas *-u- activity.AllSessionActivities
lambda.encounter.AllEncounterLambdas *-u- activity.AllEncounterActivities
lambda.creature.AllCreatureLambdas *-u- activity.AllCreatureActivities
lambda.spell.AllSpellLambdas *-u- activity.AllSpellActivities
lambda.templateCreature.AllTemplateCreatureLambdas *-u- activity.TemplateCreatureActivities
lambda.templateSpell.AllTemplateSpellLambdas *-u- activity.TemplateSpellActivities

newpage
allowmixing
class dynamodb.dao.SessionDao{}
class dynamodb.dao.EncounterDao{}
class dynamodb.dao.CreatureDao{}
class dynamodb.dao.SpellDao{}
interface dynamodb.dao.BeholderDao{}

dynamodb.dao.SessionDao ..* dynamodb.dao.BeholderDao
dynamodb.dao.EncounterDao ..* dynamodb.dao.BeholderDao
dynamodb.dao.CreatureDao ..* dynamodb.dao.BeholderDao
dynamodb.dao.SpellDao ..* dynamodb.dao.BeholderDao

class dynamodb.models.Action{}
class dynamodb.models.Creature{}
class dynamodb.models.Effect{}
class dynamodb.models.Encounter{}
class dynamodb.models.Session{}
class dynamodb.models.Spell{}
interface dynamodb.models.BeholderObject{}

dynamodb.models.Action ..* dynamodb.models.BeholderObject
dynamodb.models.Creature ..* dynamodb.models.BeholderObject
dynamodb.models.Encounter ..* dynamodb.models.BeholderObject
dynamodb.models.Session ..* dynamodb.models.BeholderObject
dynamodb.models.Spell ..* dynamodb.models.BeholderObject

dynamodb.models.Session *-u- dynamodb.models.Encounter
dynamodb.models.Encounter *-u- dynamodb.models.Creature
dynamodb.models.Creature *-u- dynamodb.models.Spell
dynamodb.models.Creature *-u- dynamodb.models.Action
dynamodb.models.Creature *-u- dynamodb.models.Effect
dynamodb.models.Spell *-u- dynamodb.models.Effect
dynamodb.models.Action *-u- dynamodb.models.Effect
@enduml